# 빌드 스테이지
FROM oven/bun:alpine as builder

WORKDIR /app

# ENV PATH="/root/.bun/bin:$PATH"

# Dependency 설치
COPY package.json bun.lockb ./

RUN bun install

# 소스코드 복사
COPY . .

# 빌드
RUN bun run build

# 베포용 빌드 이미지 스테이지
FROM oven/bun:latest

# 프로덕션 환경변수
# ENV NODE_ENV=production

WORKDIR /app

# ENV PATH="/root/.bun/bin:$PATH"

# 빌드된 파일들만 복사
COPY --from=builder /node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/dist ./dist

# 포트
EXPOSE 3000

# 실행
CMD ["bun", "dist/main.js"]