-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "thumbnail" SET DATA TYPE VARCHAR(300),
ALTER COLUMN "videoUrl" DROP NOT NULL,
ALTER COLUMN "fileUrl" DROP NOT NULL;

-- AlterTable
ALTER TABLE "SyncDb" ALTER COLUMN "lastSyncedAt" SET DEFAULT '2000-01-01 00:00:00';
