import type { Resume } from "@prisma/client";

export const mockResumes: Resume[] = [
    {
        id: 1,
        title: '이력서 테스트',
        url: 'https://test.com/resume.pdf',
        isMain: false,
        category: 'PORTFOLIO',
        position: 'BACKEND',
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: 1,
        isDeleted: false,
        likeCount: 0,
        viewCount: 0,
    },
    {
        id: 2,
        title: '이력서 테스트2',
        url: 'https://test2.com/resume.pdf',
        isMain: false,
        category: 'PORTFOLIO',
        position: 'BACKEND',
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: 1,
        isDeleted: false,
        likeCount: 0,
        viewCount: 0,
    },
    {
        id: 3,
        title: '이력서 테스트3',
        url: 'https://test3.com/resume.pdf',
        isMain: false,
        category: 'PORTFOLIO',
        position: 'BACKEND',
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: 2,
        isDeleted: false,
        likeCount: 0,
        viewCount: 0,
    },
    {
        id: 4,
        title: '이력서 테스트4 (삭제됨)',
        url: 'https://test4.com/resume.pdf',
        isMain: false,
        category: 'PORTFOLIO',
        position: 'BACKEND',
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: 1,
        isDeleted: true,
        likeCount: 0,
        viewCount: 0,
    }
];

export const mockUsers = [
    {
        id: 1,
        name: '김테커',
        email: 'test@example.com',
        roleId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        isDeleted: false,
        stack: ['BACKEND'],
        nickname: '김테커',
        year: 4,
        password: 'passW0rd1!',
        isLft: false,
        githubUrl: 'https://github.com/test',
        mainPosition: 'BACKEND',
        subPosition: 'FRONTEND',
        tistoryUrl: null,
        velogUrl: null,
        mediumUrl: null,
        school: '테커대학교',
        grade: '1',
        isAuth: false,
        profileImage: 'https://test.com/image.jpg'
    },
    {
        id: 2,
        name: '김테커2',
        email: 'test2@example.com',
        roleId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        isDeleted: false,
        stack: ['BACKEND'],
        nickname: '김테커2',
        year: 4,
        password: 'passW0rd1!',
        isLft: false,
        githubUrl: 'https://github.com/test',
        mainPosition: 'BACKEND',
        subPosition: 'FRONTEND',
        tistoryUrl: null,
        velogUrl: null,
        mediumUrl: null,
        school: '테커대학교',
        grade: '1',
        isAuth: false,
        profileImage: 'https://test.com/image.jpg'
    }
]

